<?php
	namespace ewgraCmsModules;
	
	/**
	 * Generated by meta builder!
	 * Do not edit this file!
	*/
	
	ClassesAutoloader::me()->addSearchDirectory(dirname(__FILE__));
	
	\ewgraCms\Language::da()->addLinkedCacher(NavigationData::da());
?>