<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNavigationData
	{
		private $id = null;
		
		private $navigationId = null;
		
		/**
		 * @var Navigation
		 */
		private $navigation = null;
		
		private $languageId = null;
		
		/**
		 * @var Language
		 */
		private $language = null;
		
		private $text = null;
		
		/**
		 * @return NavigationDataDA
		 */
		public static function da()
		{
			return NavigationDataDA::me();
		}
		
		/**
		 * @return AutoNavigationData
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoNavigationData
		 */
		public function setNavigationId($navigationId)
		{
			$this->navigation = null;
			$this->navigationId = $navigationId;

			return $this;
		}
		
		public function getNavigationId()
		{
			return $this->navigationId;
		}
		
		/**
		 * @return AutoNavigationData
		 */
		public function setNavigation(Navigation $navigation)
		{
			$this->navigationId = $navigation->getId();
			$this->navigation = $navigation;

			return $this;
		}
		
		/**
		 * @return Navigation
		 */
		public function getNavigation()
		{
			if (!$this->navigation && $this->getNavigationId())
				$this->navigation = Navigation::da()->getById($this->getNavigationId());
				
			return $this->navigation;
		}
		
		/**
		 * @return AutoNavigationData
		 */
		public function setLanguageId($languageId)
		{
			$this->language = null;
			$this->languageId = $languageId;

			return $this;
		}
		
		public function getLanguageId()
		{
			return $this->languageId;
		}
		
		/**
		 * @return AutoNavigationData
		 */
		public function setLanguage(Language $language)
		{
			$this->languageId = $language->getId();
			$this->language = $language;

			return $this;
		}
		
		/**
		 * @return Language
		 */
		public function getLanguage()
		{
			if (!$this->language && $this->getLanguageId())
				$this->language = Language::da()->getById($this->getLanguageId());
				
			return $this->language;
		}
		
		/**
		 * @return AutoNavigationData
		 */
		public function setText($text)
		{
			$this->text = $text;

			return $this;
		}
		
		public function getText()
		{
			return $this->text;
		}
	}
?>