<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNavigationCategory
	{
		private $id = null;

		private $alias = null;

		/**
		 * @return NavigationCategoryDA
		 */
		public static function da()
		{
			return NavigationCategoryDA::me();
		}

		/**
		 * @return NavigationCategoryProto
		 */
		public static function proto()
		{
			return NavigationCategoryProto::me();
		}

		/**
		 * @return AutoNavigationCategory
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		/**
		 * @return AutoNavigationCategory
		 */
		public function setAlias($alias)
		{
			$this->alias = $alias;

			return $this;
		}

		public function getAlias()
		{
			return $this->alias;
		}
	}
?>