<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoUserAccountTransactionProto extends \ewgraFramework\ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"account" =>  "account_id", 
			"created" =>  "created", 
			"value" =>  "value"
		);
	}
?>