<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	use ewgraFramework\StringUtils;

	final class RightDA extends AutoRightDA
	{
		/**
		 * @return RightDA
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}

		/**
		 * @return Right
		 */
		public function getByAlias($alias)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery("SELECT * FROM ".$this->getTable()." WHERE upper(alias) = upper(?)")->
				setValues(array($alias))
			);
		}

		/**
		 * @return Right
		 */
		public function getByAliases(array $aliases)
		{
			$upperAliases = array();

			foreach ($aliases as $alias)
				$upperAliases[] = StringUtils::toUpper($alias);

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery("SELECT * FROM ".$this->getTable()." WHERE upper(alias) IN(?)")->
				setValues(array($upperAliases))
			);
		}

		public function getByInheritanceIds(array $ids)
		{
			$dbQuery = "
				SELECT t1.* FROM ".$this->getTable()." t1
				INNER JOIN ".$this->escapeTable('right_inheritance')." t2
					ON(t2.right_id = t1.id)
				WHERE t2.child_right_id IN (?)
			";

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($ids))
			);
		}
	}
?>