<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class Bill extends AutoBill
	{
		/**
		 * @return Bill
		 */
		public static function create()
		{
			return new self;
		}

		public function reduceBalance($value)
		{
			$this->setBalance($this->getBalance()-$value);
			return $this;
		}

		public function addBalance($value)
		{
			$this->setBalance($this->getBalance()+$value);
			return $this;
		}
	}
?>