<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoBill
	{
		private $id = null;

		/**
		 * @var \ewgraFramework\DateTime
		 */
		private $created = null;

		private $balance = null;

		/**
		 * @return BillDA
		 */
		public static function da()
		{
			return BillDA::me();
		}

		/**
		 * @return BillProto
		 */
		public static function proto()
		{
			return BillProto::me();
		}

		/**
		 * @return AutoBill
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		/**
		 * @return AutoBill
		 */
		public function setCreated(\ewgraFramework\DateTime $created)
		{
			$this->created = $created;

			return $this;
		}

		/**
		 * @return \ewgraFramework\DateTime
		 */
		public function getCreated()
		{
			return $this->created;
		}

		/**
		 * @return AutoBill
		 */
		public function setBalance($balance)
		{
			$this->balance = $balance;

			return $this;
		}

		public function getBalance()
		{
			return $this->balance;
		}
	}
?>