<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoBillTransaction
	{
		private $id = null;

		/**
		 * @var \ewgraFramework\DateTime
		 */
		private $created = null;

		private $purpose = null;

		private $debitId = null;

		/**
		 * @var Bill
		 */
		private $debit = null;

		private $creditId = null;

		/**
		 * @var Bill
		 */
		private $credit = null;

		private $value = null;

		/**
		 * @return BillTransactionDA
		 */
		public static function da()
		{
			return BillTransactionDA::me();
		}

		/**
		 * @return BillTransactionProto
		 */
		public static function proto()
		{
			return BillTransactionProto::me();
		}

		/**
		 * @return AutoBillTransaction
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		/**
		 * @return AutoBillTransaction
		 */
		public function setCreated(\ewgraFramework\DateTime $created)
		{
			$this->created = $created;

			return $this;
		}

		/**
		 * @return \ewgraFramework\DateTime
		 */
		public function getCreated()
		{
			return $this->created;
		}

		/**
		 * @return AutoBillTransaction
		 */
		public function setPurpose($purpose)
		{
			$this->purpose = $purpose;

			return $this;
		}

		public function getPurpose()
		{
			return $this->purpose;
		}

		/**
		 * @return AutoBillTransaction
		 */
		public function setDebitId($debitId)
		{
			$this->debit = null;
			$this->debitId = $debitId;

			return $this;
		}

		public function getDebitId()
		{
			return $this->debitId;
		}

		/**
		 * @return AutoBillTransaction
		 */
		public function setDebit(Bill $debit)
		{
			$this->debitId = $debit->getId();
			$this->debit = $debit;

			return $this;
		}

		/**
		 * @return Bill
		 */
		public function getDebit()
		{
			if (!$this->debit && $this->getDebitId())
				$this->debit = Bill::da()->getById($this->getDebitId());

			return $this->debit;
		}

		/**
		 * @return AutoBillTransaction
		 */
		public function setCreditId($creditId)
		{
			$this->credit = null;
			$this->creditId = $creditId;

			return $this;
		}

		public function getCreditId()
		{
			return $this->creditId;
		}

		/**
		 * @return AutoBillTransaction
		 */
		public function setCredit(Bill $credit)
		{
			$this->creditId = $credit->getId();
			$this->credit = $credit;

			return $this;
		}

		/**
		 * @return Bill
		 */
		public function getCredit()
		{
			if (!$this->credit && $this->getCreditId())
				$this->credit = Bill::da()->getById($this->getCreditId());

			return $this->credit;
		}

		/**
		 * @return AutoBillTransaction
		 */
		public function setValue($value)
		{
			$this->value = $value;

			return $this;
		}

		public function getValue()
		{
			return $this->value;
		}
	}
?>