<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoUserAccount
	{
		private $id = null;

		private $userId = null;

		/**
		 * @var User
		 */
		private $user = null;

		/**
		 * @var \ewgraFramework\DateTime
		 */
		private $created = null;

		private $balance = null;

		/**
		 * @return UserAccountDA
		 */
		public static function da()
		{
			return UserAccountDA::me();
		}

		/**
		 * @return UserAccountProto
		 */
		public static function proto()
		{
			return UserAccountProto::me();
		}

		/**
		 * @return AutoUserAccount
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		/**
		 * @return AutoUserAccount
		 */
		public function setUserId($userId)
		{
			$this->user = null;
			$this->userId = $userId;

			return $this;
		}

		public function getUserId()
		{
			return $this->userId;
		}

		/**
		 * @return AutoUserAccount
		 */
		public function setUser(User $user)
		{
			$this->userId = $user->getId();
			$this->user = $user;

			return $this;
		}

		/**
		 * @return User
		 */
		public function getUser()
		{
			if (!$this->user && $this->getUserId())
				$this->user = User::da()->getById($this->getUserId());

			return $this->user;
		}

		/**
		 * @return AutoUserAccount
		 */
		public function setCreated(\ewgraFramework\DateTime $created)
		{
			$this->created = $created;

			return $this;
		}

		/**
		 * @return \ewgraFramework\DateTime
		 */
		public function getCreated()
		{
			return $this->created;
		}

		/**
		 * @return AutoUserAccount
		 */
		public function setBalance($balance)
		{
			$this->balance = $balance;

			return $this;
		}

		public function getBalance()
		{
			return $this->balance;
		}
	}
?>