<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class NavigationDA extends AutoNavigationDA
	{
		/**
		 * @return NavigationDA
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}

		public function getByCategoryIds(array $ids)
		{
			$dbQuery = "
				SELECT * FROM ".$this->getTable()."
				WHERE category_id = ? AND status = ".NavigationStatus::NORMAL."
				ORDER BY position ASC
			";

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($ids))
			);
		}

		/**
		 * @return Navigation
		 */
		public function getById($id)
		{
			$dbQuery = 'SELECT * FROM '.$this->getTable().' WHERE id=?';

			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($id))
			);
		}
	}
?>