<?php
	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class NavigationDataDA extends AutoNavigationDataDA
	{
		/**
		 * @return NavigationDataDA
		 */
		public static function me()
		{
			return parent::getInstance(__CLASS__);
		}

		/**
		 * @return NavigationData
		 */
		public function get(Navigation $navigation, Language $language)
		{
			$dbQuery = "
				SELECT * FROM " . $this->getTable() . "
				WHERE navigation_id = ? AND language_id = ?
			";
			
			return $this->getCachedByQuery(
				DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($navigation->getId(), $language->getId()))
			);
		}
		
		public function getList(
			array $navigationList = null,
			array $languageList = null
		) {
			$dbQuery = "SELECT * FROM " . $this->getTable();

			$queryParts = array('1');
			$params = array();
			
			if ($navigationList) {
				$params[] = ArrayUtils::getObjectIds($navigationList);
				$queryParts[] = 'navigation_id IN(?)';
			}
			
			if ($languageList) {
				$params[] = ArrayUtils::getObjectIds($languageList);
				$queryParts[] = 'language_id IN(?)';
			}
			
			$dbQuery .= ' WHERE '.join(' AND ', $queryParts);
			
			return $this->getListCachedByQuery(
				DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($params)
			);
		}
	}
?>