<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class NavigationCategoryDA extends AutoNavigationCategoryDA
	{
		/**
		 * @return NavigationCategoryDA
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}

		/**
		 * @return NavigationCategory
		 */
		public function getByAlias($alias)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE uper(alias) = upper(?)')->
				setValues(array($alias))
			);
		}
	}
?>