<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class NavigationDataDA extends AutoNavigationDataDA
	{
		/**
		 * @return NavigationDataDA
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}

		/**
		 * @return NavigationData
		 */
		public function get(Navigation $navigation, \ewgraCms\Language $language)
		{
			$dbQuery = "
				SELECT * FROM " . $this->getTable() . "
				WHERE navigation_id = ? AND language_id = ?
			";

			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($navigation->getId(), $language->getId()))
			);
		}

		public function getList(
			array $navigationList = null,
			array $languageList = null
		) {
			$dbQuery = "SELECT * FROM " . $this->getTable();

			$queryParts = array();
			$params = array();

			if ($navigationList) {
				$params[] = \ewgraFramework\ArrayUtils::getObjectIds($navigationList);
				$queryParts[] = 'navigation_id IN(?)';
			}

			if ($languageList) {
				$params[] = \ewgraFramework\ArrayUtils::getObjectIds($languageList);
				$queryParts[] = 'language_id IN(?)';
			}

			if ($queryParts)
				$dbQuery .= ' WHERE '.join(' AND ', $queryParts);

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($params)
			);
		}
	}
?>