<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this file!
	*/
	
	ClassesAutoloader::me()->addSearchDirectories(array(dirname(__FILE__)));
	
	Language::da()->addLinkedCacher(ContentData::da());
?>