<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this file!
	*/
	
	ClassesAutoloader::me()->addSearchDirectory(dirname(__FILE__));
	
	Page::da()->addLinkedCacher(PageRight::da());
	Page::da()->addLinkedCacher(PageRight::da());
?>