<?php
	namespace ewgraCmsModules;
	
	/**
	 * Generated by meta builder!
	 * Do not edit this file!
	*/
	
	ClassesAutoloader::me()->addSearchDirectory(dirname(__FILE__), __NAMESPACE__);
	
	Page::da()->addLinkedCacher(PageRight::da());
	Right::da()->addLinkedCacher(PageRight::da());
?>