<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class NewsDA extends AutoNewsDA
	{
		/**
		 * @return NewsDA
		 */
		public static function me()
		{
			return parent::getInstance(__CLASS__);
		}

		public function getList($limit = null)
		{
			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery(
					"SELECT * FROM ".$this->getTable()
					.' ORDER BY created DESC '
					.($limit ? $this->db()->getDialect()->getLimit($limit) : null)
				)
			);
		}

		/**
		 * @return News
		 */
		public function getById($id)
		{
			$dbQuery = 'SELECT * FROM '.$this->getTable().' WHERE id=?';

			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($id))
			);
		}

		/**
		 * @return News
		 */
		public function getByUri($uri)
		{
			$dbQuery = 'SELECT * FROM '.$this->getTable().' WHERE uri=?';

			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($uri))
			);
		}
	}
?>