<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class NewsDA extends AutoNewsDA
	{
		/**
		 * @return NewsDA
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}

		public function getList($limit = null)
		{
			$dialect = $this->db()->getDialect();

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery(
					"SELECT * FROM ".$this->getTable()
					.' ORDER BY '.$dialect->createOrder('created')->desc()->toString($dialect).' '
					.($limit ? $dialect->getLimit($limit) : null)
				)
			);
		}

		/**
		 * @return News
		 */
		public function getByUri($uri)
		{
			$dbQuery = 'SELECT * FROM '.$this->getTable().' WHERE upper(uri)=upper(?)';

			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($uri))
			);
		}
	}
?>