<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageRight
	{
		private $id = null;

		private $pageId = null;

		/**
		 * @var \ewgraCms\Page
		 */
		private $page = null;

		private $rightId = null;

		/**
		 * @var Right
		 */
		private $right = null;

		private $redirectPageId = null;

		/**
		 * @var \ewgraCms\Page
		 */
		private $redirectPage = null;

		/**
		 * @return PageRightDA
		 */
		public static function da()
		{
			return PageRightDA::me();
		}

		/**
		 * @return AutoPageRight
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		/**
		 * @return AutoPageRight
		 */
		public function setPageId($pageId)
		{
			$this->page = null;
			$this->pageId = $pageId;

			return $this;
		}

		public function getPageId()
		{
			return $this->pageId;
		}

		/**
		 * @return AutoPageRight
		 */
		public function setPage(\ewgraCms\Page $page)
		{
			$this->pageId = $page->getId();
			$this->page = $page;

			return $this;
		}

		/**
		 * @return \ewgraCms\Page
		 */
		public function getPage()
		{
			if (!$this->page && $this->getPageId())
				$this->page = \ewgraCms\Page::da()->getById($this->getPageId());

			return $this->page;
		}

		/**
		 * @return AutoPageRight
		 */
		public function setRightId($rightId)
		{
			$this->right = null;
			$this->rightId = $rightId;

			return $this;
		}

		public function getRightId()
		{
			return $this->rightId;
		}

		/**
		 * @return AutoPageRight
		 */
		public function setRight(Right $right)
		{
			$this->rightId = $right->getId();
			$this->right = $right;

			return $this;
		}

		/**
		 * @return Right
		 */
		public function getRight()
		{
			if (!$this->right && $this->getRightId())
				$this->right = Right::da()->getById($this->getRightId());

			return $this->right;
		}

		/**
		 * @return AutoPageRight
		 */
		public function setRedirectPageId($redirectPageId)
		{
			$this->redirectPage = null;
			$this->redirectPageId = $redirectPageId;

			return $this;
		}

		public function getRedirectPageId()
		{
			return $this->redirectPageId;
		}

		/**
		 * @return AutoPageRight
		 */
		public function setRedirectPage(\ewgraCms\Page $redirectPage)
		{
			$this->redirectPageId = $redirectPage->getId();
			$this->redirectPage = $redirectPage;

			return $this;
		}

		/**
		 * @return \ewgraCms\Page
		 */
		public function getRedirectPage()
		{
			if (!$this->redirectPage && $this->getRedirectPageId())
				$this->redirectPage = \ewgraCms\Page::da()->getById($this->getRedirectPageId());

			return $this->redirectPage;
		}
	}
?>