<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class UserDA extends AutoUserDA
	{
		/**
		 * @return UserDA
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}

		/**
		 * @return User
		 */
		public function getByLogin($login)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE upper(login) = upper(?)')->
				setValues(array($login))
			);
		}

		/**
		 * @return User
		 */
		public function getByEmail($email)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE upper(email) = upper(?)')->
				setValues(array($email))
			);
		}

		/**
		 * @return User
		 */
		public function getByRight(Right $right)
		{
			$dbQuery = '
				SELECT t1.*
				FROM '.$this->getTable().' t1
				INNER JOIN '.UserRight::da()->getTable().' t2
					ON(t2.user_id = t1.id AND t2.right_id = ?)
				';

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues(array($right->getId()))
			);
		}
	}
?>