<?php
	namespace ewgraCmsModules;
	
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNavigationCategoryDA extends \ewgraCms\DatabaseRequester
	{
		protected $tableAlias = 'NavigationCategory';
		
		/**
		 * @return NavigationCategory
		 */
		public function insert(NavigationCategory $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParts = array();
			$queryParams = array();
			
			if (!is_null($object->getAlias())) {
				$queryParts[] = '`alias` = ?';
				$queryParams[] = $object->getAlias();
			}
			
			$dbQuery .= join(', ', $queryParts);
			
			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);
			
			$object->setId($this->db()->getInsertedId());
			
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return AutoNavigationCategoryDA
		 */
		public function save(NavigationCategory $object)
		{
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';
			
			$queryParts = array();
			$whereParts = array();
			$queryParams = array();
			
			$queryParts[] = '`alias` = ?';
			$queryParams[] = $object->getAlias();
			
			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);
			
			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);
			 
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return AutoNavigationCategoryDA
		 */
		public function delete(NavigationCategory $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();
			
			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);
			 
			$object->setId(null);
			
			$this->dropCache();
			
			return $this;
		}

		/**
		 * @return NavigationCategory
		 */
		public function build(array $array)
		{
			return
				NavigationCategory::create()->
				setId($array['id'])->
				setAlias($array['alias']);
		}

		public function dropCache()
		{
			Navigation::da()->dropCache();
			return parent::dropCache();
		}
	}
?>