<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNavigationDataDA extends CmsDatabaseRequester
	{
		protected $tableAlias = 'NavigationData';
		
		/**
		 * @return NavigationData
		 */
		public function insert(NavigationData $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParts = array();
			$queryParams = array();
			
			if (!is_null($object->getNavigationId())) {
				$queryParts[] = 'navigation_id = ?';
				$queryParams[] = $object->getNavigationId();
			}
			
			if (!is_null($object->getLanguageId())) {
				$queryParts[] = 'language_id = ?';
				$queryParams[] = $object->getLanguageId();
			}
			
			if (!is_null($object->getText())) {
				$queryParts[] = 'text = ?';
				$queryParams[] = $object->getText();
			}
			
			$dbQuery .= join(', ', $queryParts);
			
			$this->db()->query(
				DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);
			
			$object->setId($this->db()->getInsertedId());
			
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return AutoNavigationDataDA
		 */
		public function save(NavigationData $object)
		{
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';
			
			$queryParts = array();
			$whereParts = array();
			$queryParams = array();
			
			$queryParts[] = 'navigation_id = ?';
			$queryParams[] = $object->getNavigationId();
			$queryParts[] = 'language_id = ?';
			$queryParams[] = $object->getLanguageId();
			$queryParts[] = 'text = ?';
			$queryParams[] = $object->getText();
			
			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			Assert::isNotEmpty($whereParts);
			
			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);
			 
			$this->dropCache();
			
			return $object;
		}

		/**
		 * @return NavigationData
		 */
		protected function build(array $array)
		{
			return
				NavigationData::create()->
				setId($array['id'])->
				setNavigationId($array['navigation_id'])->
				setLanguageId($array['language_id'])->
				setText($array['text']);
		}
	}
?>