<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageRightProto extends \ewgraFramework\ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"page" =>  "page_id", 
			"right" =>  "right_id", 
			"redirectPage" =>  "redirect_page_id"
		);
	}
?>