<?php
	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class PageRightDA extends AutoPageRightDA
	{
		/**
		 * @return PageRightDA
		 */
		public static function me()
		{
			return parent::getInstance(__CLASS__);
		}

		public function getByPage(Page $page)
		{
			return $this->getListCachedByQuery(
				DatabaseQuery::create()->
				setQuery("SELECT * FROM ".$this->getTable()." WHERE page_id = ?")->
				setValues(array($page->getId()))
			);
		}
	}
?>