<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNews
	{
		private $id = null;

		private $uri = null;

		private $created = null;

		private $modified = null;

		/**
		 * @return NewsDA
		 */
		public static function da()
		{
			return NewsDA::me();
		}

		/**
		 * @return NewsProto
		 */
		public static function proto()
		{
			return NewsProto::me();
		}

		/**
		 * @return AutoNews
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		public function hasId()
		{
			return ($this->id !== null);
		}

		/**
		 * @return AutoNews
		 */
		public function setUri($uri)
		{
			$this->uri = $uri;

			return $this;
		}

		public function getUri()
		{
			return $this->uri;
		}

		/**
		 * @return AutoNews
		 */
		public function setCreated($created)
		{
			$this->created = $created;

			return $this;
		}

		public function getCreated()
		{
			return $this->created;
		}

		/**
		 * @return AutoNews
		 */
		public function setModified($modified)
		{
			$this->modified = $modified;

			return $this;
		}

		public function getModified()
		{
			return $this->modified;
		}
	}
?>