<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNewsData
	{
		private $id = null;

		private $newsId = null;

		/**
		 * @var News
		 */
		private $news = null;

		private $languageId = null;

		/**
		 * @var \ewgraCms\Language
		 */
		private $language = null;

		private $title = null;

		private $shortText = null;

		private $text = null;

		/**
		 * @return NewsDataDA
		 */
		public static function da()
		{
			return NewsDataDA::me();
		}

		/**
		 * @return NewsDataProto
		 */
		public static function proto()
		{
			return NewsDataProto::me();
		}

		/**
		 * @return AutoNewsData
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		public function hasId()
		{
			return ($this->id !== null);
		}

		/**
		 * @return AutoNewsData
		 */
		public function setNewsId($newsId)
		{
			$this->news = null;
			$this->newsId = $newsId;

			return $this;
		}

		public function getNewsId()
		{
			return $this->newsId;
		}

		/**
		 * @return AutoNewsData
		 */
		public function setNews(News $news)
		{
			$this->newsId = $news->getId();
			$this->news = $news;

			return $this;
		}

		/**
		 * @return News
		 */
		public function getNews()
		{
			if (!$this->news && $this->getNewsId())
				$this->news = News::da()->getById($this->getNewsId());

			return $this->news;
		}

		/**
		 * @return AutoNewsData
		 */
		public function setLanguageId($languageId)
		{
			$this->language = null;
			$this->languageId = $languageId;

			return $this;
		}

		public function getLanguageId()
		{
			return $this->languageId;
		}

		/**
		 * @return AutoNewsData
		 */
		public function setLanguage(\ewgraCms\Language $language)
		{
			$this->languageId = $language->getId();
			$this->language = $language;

			return $this;
		}

		/**
		 * @return \ewgraCms\Language
		 */
		public function getLanguage()
		{
			if (!$this->language && $this->getLanguageId())
				$this->language = \ewgraCms\Language::da()->getById($this->getLanguageId());

			return $this->language;
		}

		/**
		 * @return AutoNewsData
		 */
		public function setTitle($title)
		{
			$this->title = $title;

			return $this;
		}

		public function getTitle()
		{
			return $this->title;
		}

		/**
		 * @return AutoNewsData
		 */
		public function setShortText($shortText)
		{
			$this->shortText = $shortText;

			return $this;
		}

		public function getShortText()
		{
			return $this->shortText;
		}

		/**
		 * @return AutoNewsData
		 */
		public function setText($text)
		{
			$this->text = $text;

			return $this;
		}

		public function getText()
		{
			return $this->text;
		}
	}
?>