<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNewsDataDA extends \ewgraCms\DatabaseRequester
	{
		protected $tableAlias = 'news_data';

		/**
		 * @return NewsData
		 */
		public function insert(NewsData $object)
		{
			$dialect = $this->db()->getDialect();

			$dbQuery = 'INSERT INTO '.$this->getTable().' ';
			$fields = array();
			$fieldValues = array();
			$values = array();
			$fields[] = $dialect->escapeField('news_id');
			$fieldValues[] = '?';
			$values[] = $object->getNewsId();
			$fields[] = $dialect->escapeField('language_id');
			$fieldValues[] = '?';
			$values[] = $object->getLanguageId();
			$fields[] = $dialect->escapeField('title');
			$fieldValues[] = '?';
			$values[] = $object->getTitle();
			$fields[] = $dialect->escapeField('short_text');
			$fieldValues[] = '?';
			$values[] = $object->getShortText();
			$fields[] = $dialect->escapeField('text');
			$fieldValues[] = '?';
			$values[] = $object->getText();
			$dbQuery .= '('.join(', ', $fields).') VALUES ';
			$dbQuery .= '('.join(', ', $fieldValues).')';

			$dbResult =
				$this->db()->insertQuery(
					\ewgraFramework\DatabaseInsertQuery::create()->
					setPrimaryField('id')->
					setQuery($dbQuery)->
					setValues($values)
				);

			$object->setId($dbResult->getInsertedId());

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoNewsDataDA
		 */
		public function save(NewsData $object)
		{
			$dialect = $this->db()->getDialect();
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = $dialect->escapeField('news_id').' = ?';
			$queryParams[] = $object->getNewsId();
			$queryParts[] = $dialect->escapeField('language_id').' = ?';
			$queryParams[] = $object->getLanguageId();
			$queryParts[] = $dialect->escapeField('title').' = ?';
			$queryParams[] = $object->getTitle();
			$queryParts[] = $dialect->escapeField('short_text').' = ?';
			$queryParams[] = $object->getShortText();
			$queryParts[] = $dialect->escapeField('text').' = ?';
			$queryParams[] = $object->getText();

			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoNewsDataDA
		 */
		public function delete(NewsData $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			$this->dropCache();

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			if (!$ids)
				return array();

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return NewsData
		 */
		public function build(array $array)
		{
			return
				NewsData::create()->
				setId($array['id'])->
				setNewsId($array['news_id'])->
				setLanguageId($array['language_id'])->
				setTitle($array['title'])->
				setShortText($array['short_text'])->
				setText($array['text']);
		}
	}
?>