<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNewsDA extends \ewgraCms\DatabaseRequester
	{
		protected $tableAlias = 'news';

		public function getTag()
		{
			return '\ewgraCmsModules\News';
		}

		/**
		 * @return array
		 */
		public function getTagList()
		{
			return array($this->getTag());
		}

		/**
		 * @return News
		 */
		public function insert(News $object)
		{
			$result = $this->rawInsert($object);
			$this->dropCache();
			return $result;
		}

		/**
		 * @return News
		 */
		public function rawInsert(News $object)
		{
			$dialect = $this->db()->getDialect();

			$dbQuery = 'INSERT INTO '.$this->getTable().' ';
			$fields = array();
			$fieldValues = array();
			$values = array();

			if ($object->hasId()) {
				$fields[] = $dialect->escapeField('id');
				$fieldValues[] = '?';
				$values[] = $object->getId();
			}

			$fields[] = $dialect->escapeField('uri');
			$fieldValues[] = '?';
			$values[] = $object->getUri();
			$fields[] = $dialect->escapeField('created');
			$fieldValues[] = '?';
			$values[] = $object->getCreated();
			$fields[] = $dialect->escapeField('modified');
			$fieldValues[] = '?';
			$values[] = $object->getModified();
			$dbQuery .= '('.join(', ', $fields).') VALUES ';
			$dbQuery .= '('.join(', ', $fieldValues).')';

			$dbResult =
				$this->db()->insertQuery(
					\ewgraFramework\DatabaseInsertQuery::create()->
					setPrimaryField('id')->
					setQuery($dbQuery)->
					setValues($values)
				);

			if (!$object->hasId())
				$object->setId($dbResult->getInsertedId());

			return $object;
		}

		/**
		 * @return AutoNewsDA
		 */
		public function save(News $object)
		{
			$result = $this->rawSave($object);
			$this->dropCache();
			return $result;
		}

		/**
		 * @return AutoNewsDA
		 */
		public function rawSave(News $object)
		{
			$dialect = $this->db()->getDialect();
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = $dialect->escapeField('uri').' = ?';
			$queryParams[] = $object->getUri();
			$queryParts[] = $dialect->escapeField('created').' = ?';
			$queryParams[] = $object->getCreated();
			$queryParts[] = $dialect->escapeField('modified').' = ?';
			$queryParams[] = $object->getModified();

			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			return $object;
		}

		/**
		 * @return AutoNewsDA
		 */
		public function delete(News $object)
		{
			$result = $this->rawDelete($object);
			$this->dropCache();
			return $result;
		}

		/**
		 * @return AutoNewsDA
		 */
		public function rawDelete(News $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			if (!$ids)
				return array();

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return News
		 */
		public function build(array $array)
		{
			return
				News::create()->
				setId($array['id'])->
				setUri($array['uri'])->
				setCreated($array['created'])->
				setModified($array['modified']);
		}
	}
?>