<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNewsDataDA extends \ewgraCms\DatabaseRequester
	{
		protected $tableAlias = 'NewsData';

		/**
		 * @return NewsData
		 */
		public function insert(NewsData $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParts = array();
			$queryParams = array();

			if (!is_null($object->getNewsId())) {
				$queryParts[] = '`news_id` = ?';
				$queryParams[] = $object->getNewsId();
			}

			if (!is_null($object->getLanguageId())) {
				$queryParts[] = '`language_id` = ?';
				$queryParams[] = $object->getLanguageId();
			}

			if (!is_null($object->getTitle())) {
				$queryParts[] = '`title` = ?';
				$queryParams[] = $object->getTitle();
			}

			if (!is_null($object->getShortText())) {
				$queryParts[] = '`short_text` = ?';
				$queryParams[] = $object->getShortText();
			}

			if (!is_null($object->getText())) {
				$queryParts[] = '`text` = ?';
				$queryParams[] = $object->getText();
			}

			$dbQuery .= join(', ', $queryParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$object->setId($this->db()->getInsertedId());

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoNewsDataDA
		 */
		public function save(NewsData $object)
		{
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = '`news_id` = ?';
			$queryParams[] = $object->getNewsId();
			$queryParts[] = '`language_id` = ?';
			$queryParams[] = $object->getLanguageId();
			$queryParts[] = '`title` = ?';
			$queryParams[] = $object->getTitle();
			$queryParts[] = '`short_text` = ?';
			$queryParams[] = $object->getShortText();
			$queryParts[] = '`text` = ?';
			$queryParams[] = $object->getText();

			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoNewsDataDA
		 */
		public function delete(NewsData $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			$this->dropCache();

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return NewsData
		 */
		public function build(array $array)
		{
			return
				NewsData::create()->
				setId($array['id'])->
				setNewsId($array['news_id'])->
				setLanguageId($array['language_id'])->
				setTitle($array['title'])->
				setShortText($array['short_text'])->
				setText($array['text']);
		}
	}
?>