<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class BillTransactionDA extends AutoBillTransactionDA
	{
		/**
		 * @return BillTransactionDA
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}

		public function getListByBill(Bill $bill, \ewgraFramework\Pager $pager)
		{
			$dialect = $this->db()->getDialect();

			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('
					SELECT * FROM '.$this->getTable().' WHERE credit_id=? OR debit_id=?
					ORDER BY created DESC
					'.$dialect->getLimitByPager($pager).'
				')->
				setValues(array($bill->getId(), $bill->getId()))
			);
		}

		public function getCountByBill(Bill $bill)
		{
			$arr = $this->getCustomCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('
					SELECT count(*) as cnt FROM '.$this->getTable().'
					WHERE credit_id=? OR debit_id=?
				')->
				setValues(array($bill->getId(), $bill->getId())),
				array($this->getTag())
			);

			return $arr['cnt'];
		}
	}
?>