<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoRightDA extends \ewgraCms\DatabaseRequester
	{
		protected $tableAlias = 'Right';

		/**
		 * @return Right
		 */
		public function insert(Right $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParts = array();
			$queryParams = array();

			if (!is_null($object->getAlias())) {
				$queryParts[] = '`alias` = ?';
				$queryParams[] = $object->getAlias();
			}

			if (!is_null($object->getName())) {
				$queryParts[] = '`name` = ?';
				$queryParams[] = $object->getName();
			}

			if (!is_null($object->getRole())) {
				$queryParts[] = '`role` = ?';
				$queryParams[] = $object->getRole();
			}

			$dbQuery .= join(', ', $queryParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$object->setId($this->db()->getInsertedId());

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoRightDA
		 */
		public function save(Right $object)
		{
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = '`alias` = ?';
			$queryParams[] = $object->getAlias();

			if ($object->getName() === null)
				$queryParts[] = '`name` = NULL';
			else {
				$queryParts[] = '`name` = ?';
				$queryParams[] = $object->getName();
			}


			if ($object->getRole() === null)
				$queryParts[] = '`role` = NULL';
			else {
				$queryParts[] = '`role` = ?';
				$queryParams[] = $object->getRole();
			}


			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoRightDA
		 */
		public function delete(Right $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			$this->dropCache();

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return Right
		 */
		public function build(array $array)
		{
			return
				Right::create()->
				setId($array['id'])->
				setAlias($array['alias'])->
				setName($array['name'])->
				setRole($array['role'] == null ? null : $array['role'] == true);
		}
	}
?>