<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoRightDA extends \ewgraCms\DatabaseRequester
	{
		protected $tableAlias = 'right';

		/**
		 * @return Right
		 */
		public function insert(Right $object)
		{
			$dialect = $this->db()->getDialect();

			$dbQuery = 'INSERT INTO '.$this->getTable().' ';
			$fields = array();
			$fieldValues = array();
			$values = array();
			$fields[] = $dialect->escapeField('alias');
			$fieldValues[] = '?';
			$values[] = $object->getAlias();
			$fields[] = $dialect->escapeField('name');
			$fieldValues[] = '?';

			if ($object->getName() === null)
				$values[] = null;
			else {
				$values[] = $object->getName();
			}

			$fields[] = $dialect->escapeField('role');
			$fieldValues[] = '?';

			if ($object->getRole() === null)
				$values[] = null;
			else {
				$values[] = $object->getRole();
			}

			$dbQuery .= '('.join(', ', $fields).') VALUES ';
			$dbQuery .= '('.join(', ', $fieldValues).')';

			$dbResult =
				$this->db()->insertQuery(
					\ewgraFramework\DatabaseInsertQuery::create()->
					setPrimaryField('id')->
					setQuery($dbQuery)->
					setValues($values)
				);

			$object->setId($dbResult->getInsertedId());

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoRightDA
		 */
		public function save(Right $object)
		{
			$dialect = $this->db()->getDialect();
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = $dialect->escapeField('alias').' = ?';
			$queryParams[] = $object->getAlias();

			if ($object->getName() === null)
				$queryParts[] = $dialect->escapeField('name').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('name').' = ?';
				$queryParams[] = $object->getName();
			}


			if ($object->getRole() === null)
				$queryParts[] = $dialect->escapeField('role').' = NULL';
			else {
				$queryParts[] = $dialect->escapeField('role').' = ?';
				$queryParams[] = $object->getRole();
			}


			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoRightDA
		 */
		public function delete(Right $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			$this->dropCache();

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return Right
		 */
		public function build(array $array)
		{
			return
				Right::create()->
				setId($array['id'])->
				setAlias($array['alias'])->
				setName($array['name'])->
				setRole($array['role'] === null ? null : $array['role'] == true);
		}
	}
?>