<?php
	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class UserRightDA extends AutoUserRightDA
	{
		/**
		 * @return UserRightDA
		 */
		public static function me()
		{
			return parent::getInstance(__CLASS__);
		}

		public function getRightIdsByUser(User $user)
		{
			$userRights = $this->getByUser($user);
			
			$rightIds = array();
			
			foreach ($userRights as $userRight)
				$rightIds[] = $userRight->getRightId();
			
			return $rightIds;
		}
		
		public function getByUser(User $user)
		{
			return $this->getListCachedByQuery(
				DatabaseQuery::create()->
				setQuery("SELECT * FROM ".$this->getTable()." WHERE user_id = ?")->
				setValues(array($user->getId()))
			);
		}
	}
?>