<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoContentData
	{
		private $id = null;
		
		private $contentId = null;
		
		/**
		 * @var Content
		 */
		private $content = null;
		
		private $languageId = null;
		
		/**
		 * @var Language
		 */
		private $language = null;
		
		private $text = null;
		
		/**
		 * @return ContentDataDA
		 */
		public static function da()
		{
			return ContentDataDA::me();
		}
		
		/**
		 * @return AutoContentData
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoContentData
		 */
		public function setContentId($contentId)
		{
			$this->content = null;
			$this->contentId = $contentId;

			return $this;
		}
		
		public function getContentId()
		{
			return $this->contentId;
		}
		
		/**
		 * @return AutoContentData
		 */
		public function setContent(Content $content)
		{
			$this->contentId = $content->getId();
			$this->content = $content;

			return $this;
		}
		
		/**
		 * @return Content
		 */
		public function getContent()
		{
			if (!$this->content && $this->getContentId())
				$this->content = Content::da()->getById($this->getContentId());
				
			return $this->content;
		}
		
		/**
		 * @return AutoContentData
		 */
		public function setLanguageId($languageId)
		{
			$this->language = null;
			$this->languageId = $languageId;

			return $this;
		}
		
		public function getLanguageId()
		{
			return $this->languageId;
		}
		
		/**
		 * @return AutoContentData
		 */
		public function setLanguage(Language $language)
		{
			$this->languageId = $language->getId();
			$this->language = $language;

			return $this;
		}
		
		/**
		 * @return Language
		 */
		public function getLanguage()
		{
			if (!$this->language && $this->getLanguageId())
				$this->language = Language::da()->getById($this->getLanguageId());
				
			return $this->language;
		}
		
		/**
		 * @return AutoContentData
		 */
		public function setText($text)
		{
			$this->text = $text;

			return $this;
		}
		
		public function getText()
		{
			return $this->text;
		}
	}
?>