<?php
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoContent
	{
		private $id = null;
		
		/**
		 * @var ContentStatus
		 */
		private $status = null;
		
		/**
		 * @return ContentDA
		 */
		public static function da()
		{
			return ContentDA::me();
		}
		
		/**
		 * @return AutoContent
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}
		
		public function getId()
		{
			Assert::isNotNull($this->id);
			return $this->id;
		}
		
		/**
		 * @return AutoContent
		 */
		public function setStatus(ContentStatus $status)
		{
			$this->status = $status;

			return $this;
		}
		
		/**
		 * @return ContentStatus
		 */
		public function getStatus()
		{
			return $this->status;
		}
	}
?>