<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoUser
	{
		private $id = null;

		private $login = null;

		private $password = null;

		private $passwordSalt = null;

		private $changePasswordHash = null;

		private $changePasswordSalt = null;

		private $email = null;

		private $emailConfirmHash = null;

		private $emailConfirmSalt = null;

		/**
		 * @return UserDA
		 */
		public static function da()
		{
			return UserDA::me();
		}

		/**
		 * @return UserProto
		 */
		public static function proto()
		{
			return UserProto::me();
		}

		/**
		 * @return AutoUser
		 */
		public function setId($id)
		{
			$this->id = $id;

			return $this;
		}

		public function getId()
		{
			\ewgraFramework\Assert::isNotNull($this->id);
			return $this->id;
		}

		public function hasId()
		{
			return ($this->id !== null);
		}

		/**
		 * @return AutoUser
		 */
		public function setLogin($login)
		{
			$this->login = $login;

			return $this;
		}

		public function getLogin()
		{
			return $this->login;
		}

		/**
		 * @return AutoUser
		 */
		public function setPassword($password)
		{
			$this->password = $password;

			return $this;
		}

		public function getPassword()
		{
			return $this->password;
		}

		/**
		 * @return AutoUser
		 */
		public function setPasswordSalt($passwordSalt)
		{
			$this->passwordSalt = $passwordSalt;

			return $this;
		}

		public function getPasswordSalt()
		{
			return $this->passwordSalt;
		}

		/**
		 * @return AutoUser
		 */
		public function setChangePasswordHash($changePasswordHash = null)
		{
			$this->changePasswordHash = $changePasswordHash;

			return $this;
		}

		public function getChangePasswordHash()
		{
			return $this->changePasswordHash;
		}

		/**
		 * @return AutoUser
		 */
		public function setChangePasswordSalt($changePasswordSalt = null)
		{
			$this->changePasswordSalt = $changePasswordSalt;

			return $this;
		}

		public function getChangePasswordSalt()
		{
			return $this->changePasswordSalt;
		}

		/**
		 * @return AutoUser
		 */
		public function setEmail($email)
		{
			$this->email = $email;

			return $this;
		}

		public function getEmail()
		{
			return $this->email;
		}

		/**
		 * @return AutoUser
		 */
		public function setEmailConfirmHash($emailConfirmHash = null)
		{
			$this->emailConfirmHash = $emailConfirmHash;

			return $this;
		}

		public function getEmailConfirmHash()
		{
			return $this->emailConfirmHash;
		}

		/**
		 * @return AutoUser
		 */
		public function setEmailConfirmSalt($emailConfirmSalt = null)
		{
			$this->emailConfirmSalt = $emailConfirmSalt;

			return $this;
		}

		public function getEmailConfirmSalt()
		{
			return $this->emailConfirmSalt;
		}
	}
?>