<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoUserProto extends ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"login" =>  "login", 
			"password" =>  "password", 
			"changePasswordHash" =>  "change_password_hash", 
			"email" =>  "email", 
			"emailConfirmHash" =>  "email_confirm_hash"
		);
	}
?>