<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class ContentDA extends AutoContentDA
	{
		/**
		 * @return ContentDA
		 */
		public static function me()
		{
			return parent::getInstance(__CLASS__);
		}

		public function getByIds(array $ids)
		{
			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery(
					"SELECT * FROM ".$this->getTable()
					." WHERE id IN (?) AND status = ".ContentStatus::NORMAL
				)->
				setValues(array($ids))
			);
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery(
					"SELECT * FROM ".$this->getTable()
					." WHERE id = ? AND status = ".ContentStatus::NORMAL
				)->
				setValues(array($id))
			);
		}
	}
?>