<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder, you can edit this class
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	final class NavigationProto extends AutoNavigationProto
	{
		/**
		 * @return NavigationProto
		 * method needed for methods hinting
		 */
		public static function me()
		{
			return parent::me();
		}
	}
?>