<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this file!
	*/

	\ewgraFramework\ClassesAutoloader::me()->addSearchDirectory(dirname(__FILE__), __NAMESPACE__);

	User::da()->addLinkedCacher(UserRight::da());
	Right::da()->addLinkedCacher(UserRight::da());
?>