<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNewsProto extends \ewgraFramework\ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"uri" =>  "uri", 
			"created" =>  "created", 
			"modified" =>  "modified"
		);
	}
?>