<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoNewsDataProto extends \ewgraFramework\ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"news" =>  "news_id", 
			"language" =>  "language_id", 
			"title" =>  "title", 
			"shortText" =>  "short_text", 
			"text" =>  "text"
		);
	}
?>