<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoUserRightProto extends ProtoObject
	{
		protected $dbFields = array(
			"id" =>  "id", 
			"user" =>  "user_id", 
			"right" =>  "right_id"
		);
	}
?>