<?php
	namespace ewgraCmsModules;

	/**
	 * Generated by meta builder!
	 * Do not edit this class!
	 * @license http://www.opensource.org/licenses/bsd-license.php BSD
	 * @author Evgeniy Sokolov <ewgraf@gmail.com>
	 */
	abstract class AutoPageRightDA extends \ewgraCms\DatabaseRequester
	{
		protected $tableAlias = 'PageRight';

		/**
		 * @return PageRight
		 */
		public function insert(PageRight $object)
		{
			$dbQuery = 'INSERT INTO '.$this->getTable().' SET ';
			$queryParts = array();
			$queryParams = array();

			if (!is_null($object->getPageId())) {
				$queryParts[] = '`page_id` = ?';
				$queryParams[] = $object->getPageId();
			}

			if (!is_null($object->getRightId())) {
				$queryParts[] = '`right_id` = ?';
				$queryParams[] = $object->getRightId();
			}

			if (!is_null($object->getRedirectPageId())) {
				$queryParts[] = '`redirect_page_id` = ?';
				$queryParams[] = $object->getRedirectPageId();
			}

			$dbQuery .= join(', ', $queryParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$object->setId($this->db()->getInsertedId());

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoPageRightDA
		 */
		public function save(PageRight $object)
		{
			$dbQuery = 'UPDATE '.$this->getTable().' SET ';

			$queryParts = array();
			$whereParts = array();
			$queryParams = array();

			$queryParts[] = '`page_id` = ?';
			$queryParams[] = $object->getPageId();
			$queryParts[] = '`right_id` = ?';
			$queryParams[] = $object->getRightId();
			$queryParts[] = '`redirect_page_id` = ?';
			$queryParams[] = $object->getRedirectPageId();

			$whereParts[] = 'id = ?';
			$queryParams[] = $object->getId();
			\ewgraFramework\Assert::isNotEmpty($whereParts);

			$dbQuery .= join(', ', $queryParts).' WHERE '.join(' AND ', $whereParts);

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery($dbQuery)->
				setValues($queryParams)
			);

			$this->dropCache();

			return $object;
		}

		/**
		 * @return AutoPageRightDA
		 */
		public function delete(PageRight $object)
		{
			$dbQuery =
				'DELETE FROM '.$this->getTable().' WHERE id = '.$object->getId();

			$this->db()->query(
				\ewgraFramework\DatabaseQuery::create()->setQuery($dbQuery)
			);

			$object->setId(null);

			$this->dropCache();

			return $this;
		}

		public function getById($id)
		{
			return $this->getCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id = ?')->
				setValues(array($id))
			);
		}

		public function getByIds(array $ids)
		{
			return $this->getListCachedByQuery(
				\ewgraFramework\DatabaseQuery::create()->
				setQuery('SELECT * FROM '.$this->getTable().' WHERE id IN(?)')->
				setValues(array($ids))
			);
		}

		/**
		 * @return PageRight
		 */
		public function build(array $array)
		{
			return
				PageRight::create()->
				setId($array['id'])->
				setPageId($array['page_id'])->
				setRightId($array['right_id'])->
				setRedirectPageId($array['redirect_page_id']);
		}
	}
?>