CREATE TABLE bill (
	id bigint NOT NULL PRIMARY KEY,
	created timestamp without time zone not null default now(),
	balance numeric(10,2) not null default 0
);

CREATE TABLE bill_transaction (
	id bigint NOT NULL PRIMARY KEY,
	created timestamp without time zone not null default now(),
	debit_id bigint NOT NULL REFERENCES "bill"(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	credit_id bigint NOT NULL REFERENCES "bill"(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	value numeric(10,2) not null
);